# Generated by Django 3.2.5 on 2021-07-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_fk', to='Users.users'),
            preserve_default=False,
        ),
    ]
