# Generated by Django 3.2.5 on 2021-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0002_organizationmembership_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
