# Generated by Django 3.2.5 on 2021-07-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0003_organizationmembership_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationmembership',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='organizationmembership',
            old_name='user_id',
            new_name='user',
        ),
    ]
