# Generated by Django 3.2.5 on 2021-08-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
