# Generated by Django 3.2.5 on 2021-08-04 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20210804_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
