# Generated by Django 3.2.5 on 2021-08-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_customuser_creation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_code', models.CharField(max_length=25)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
