# Generated by Django 3.2.5 on 2021-08-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tiktokEmail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tiktokId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
