# Generated by Django 3.2.5 on 2021-08-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorAdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('platform', models.CharField(max_length=255)),
                ('execution_deadline', models.DateField()),
                ('creation_time', models.DateField(auto_now_add=True)),
                ('dreamwell_approval_time', models.DateField(blank=True, null=True)),
                ('dreamwell_rejection_time', models.DateField(blank=True, null=True)),
                ('completion_time', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CreatorCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('creation_time', models.DateField(auto_now_add=True)),
                ('completion_time', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CreatorProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=255)),
                ('creation_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorReferralInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_creator_email', models.CharField(max_length=255)),
                ('creation_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
