# Generated by Django 3.2.5 on 2021-08-04 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Brand', '0002_auto_20210804_1525'),
        ('Creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatoradcard',
            name='brand_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_camp_id_fk', to='Brand.brandcampaign'),
        ),
        migrations.AddField(
            model_name='creatoradcard',
            name='brand_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_user_id_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatoradcard',
            name='creator_campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='c_camp_id_fk', to='Creator.creatorcampaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creatoradcard',
            name='creator_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='c_user_id_fk', to='Users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creatorproductrequest',
            name='creator_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='c_user_fk', to='Users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creatorreferralinvitation',
            name='invitee_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='c_invitee_fk', to='Users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creatorreferralinvitation',
            name='inviting_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='c_invite_fk', to='Users.customuser'),
            preserve_default=False,
        ),
    ]
