# Generated by Django 3.2.5 on 2021-07-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0004_auto_20210713_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatorproductrequest',
            old_name='creator_user_id',
            new_name='creator_user',
        ),
        migrations.RenameField(
            model_name='creatorreferralinvitation',
            old_name='invitee_creator_id',
            new_name='invitee_creator',
        ),
        migrations.RenameField(
            model_name='creatorreferralinvitation',
            old_name='inviting_creator_id',
            new_name='inviting_creator',
        ),
    ]
