# Generated by Django 3.2.5 on 2021-07-14 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0005_auto_20210714_1633'),
        ('Users', '0002_users_description'),
        ('Creator', '0005_auto_20210713_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatoradcard',
            name='brand_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_camp_id_fk', to='Brand.brandcampaign'),
        ),
        migrations.AlterField(
            model_name='creatoradcard',
            name='brand_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_user_id_fk', to='Users.users'),
        ),
        migrations.AlterField(
            model_name='creatoradcard',
            name='completion_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creatoradcard',
            name='dreamwell_approval_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creatoradcard',
            name='dreamwell_rejection_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
