# Generated by Django 3.2.5 on 2021-07-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('organization_id', models.IntegerField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('user_role', models.CharField(max_length=255)),
            ],
        ),
    ]
