# Generated by Django 3.2.5 on 2021-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
