# Generated by Django 3.2.5 on 2021-07-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('platform', models.CharField(max_length=255)),
                ('execution_deadline', models.DateField()),
                ('creation_time', models.DateField(auto_now_add=True)),
                ('dreamwell_approval_time', models.DateField()),
                ('dreamwell_rejection_time', models.DateField()),
                ('completion_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BrandCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('completion_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BrandOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
