# Generated by Django 3.2.5 on 2021-07-12 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Creator', '0002_auto_20210711_2200'),
        ('Brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandadcard',
            name='brand_campaign_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='b_campaign_fk', to='Brand.brandcampaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandadcard',
            name='brand_organization_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='b_org_id', to='Brand.brandorganization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandadcard',
            name='brand_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='b_user_fk', to='Users.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandadcard',
            name='creator_campaign_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='c_campaign_fk', to='Creator.creatorcampaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandadcard',
            name='creator_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='c_user_b_ad_fk', to='Users.users'),
            preserve_default=False,
        ),
    ]
