# Generated by Django 3.2.5 on 2021-08-04 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Creator', '0001_initial'),
        ('Brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandadcard',
            name='brand_campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='b_campaign_fk', to='Brand.brandcampaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandadcard',
            name='brand_organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='b_org_id', to='Brand.brandorganization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandadcard',
            name='brand_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='b_user_fk', to='Users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandadcard',
            name='creator_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_campaign_fk', to='Creator.creatorcampaign'),
        ),
        migrations.AddField(
            model_name='brandadcard',
            name='creator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_user_b_ad_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
