# Generated by Django 3.2.5 on 2021-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0002_auto_20210711_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandadcard',
            name='description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandcampaign',
            name='description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandorganization',
            name='description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
