# Generated by Django 3.2.5 on 2021-07-14 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_users_description'),
        ('Creator', '0005_auto_20210713_1528'),
        ('Brand', '0004_auto_20210713_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandadcard',
            name='completion_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandadcard',
            name='creator_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_campaign_fk', to='Creator.creatorcampaign'),
        ),
        migrations.AlterField(
            model_name='brandadcard',
            name='creator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_user_b_ad_fk', to='Users.users'),
        ),
        migrations.AlterField(
            model_name='brandadcard',
            name='dreamwell_approval_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandadcard',
            name='dreamwell_rejection_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandcampaign',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
