# Generated by Django 3.2.5 on 2021-07-14 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0005_auto_20210714_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandadcard',
            name='brand_campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_campaign_fk', to='Brand.brandcampaign'),
        ),
    ]
