# Generated by Django 3.2.5 on 2021-07-14 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0007_alter_brandadcard_brand_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandadcard',
            name='brand_campaign',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='b_campaign_fk', to='Brand.brandcampaign'),
            preserve_default=False,
        ),
    ]
