# Generated by Django 3.2.4 on 2021-06-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer_name', models.CharField(max_length=255)),
                ('influencer_age', models.IntegerField()),
                ('influencer_location', models.CharField(max_length=255)),
                ('influencer_youtubechannel', models.CharField(max_length=255)),
                ('influencer_date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
