# Generated by Django 3.2.5 on 2021-07-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=255)),
                ('ad_description', models.TextField()),
                ('ad_payout_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_company_name', models.CharField(max_length=255)),
                ('brand_ad_campaign_in_progress', models.BooleanField(default=False)),
                ('brand_ad_cards_available', models.IntegerField(default=0)),
                ('brand_ad_cards_in_progress', models.IntegerField(default=0)),
                ('brand_ad_cards_complete', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=255)),
                ('creator_age', models.IntegerField()),
                ('creator_location', models.CharField(max_length=255)),
                ('creator_date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorYoutubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_channel_name', models.CharField(max_length=255)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.creator')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorAdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.adcard')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.creator')),
            ],
        ),
        migrations.AddField(
            model_name='adcard',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.brand'),
        ),
    ]
