# Generated by Django 3.2.4 on 2021-06-15 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=255)),
                ('ad_description', models.TextField()),
                ('ad_payout_amount', models.IntegerField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.brand')),
            ],
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencer_youtubechannel',
        ),
        migrations.CreateModel(
            name='InfluencerYoutubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer_channel_name', models.CharField(max_length=255)),
                ('influencer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.influencer')),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerAdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_card_id', models.ForeignKey(on_delete=models.SET(0), to='dashboard.adcard')),
                ('influencer_id', models.ForeignKey(on_delete=models.SET(0), to='dashboard.influencer')),
            ],
        ),
    ]
